/*
Fastah REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geofeed_structs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InRfc8805RowPlaceSearchParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InRfc8805RowPlaceSearchParams{}

// InRfc8805RowPlaceSearchParams struct for InRfc8805RowPlaceSearchParams
type InRfc8805RowPlaceSearchParams struct {
	// UTF-8 free text for the place name within the specified country and region. A comma is NOT allowed.
	CityName *string `json:"cityName,omitempty"`
	// A two-letter ISO 3166-1 alpha-2 country or territory code (alpha2Code). Use 'ZZ' if the location should not be geocoded.
	CountryCode string `json:"countryCode"`
	// An ISO 3166-2 code for the subdivision of a country (state/province/region) formatted as the hyphenated country code and subdivision, e.g. 'US-CA' for California, USA.
	RegionCode *string `json:"regionCode,omitempty"`
	// Stable, unique key assigned by the caller and echoed back verbatim in the matching result row. Use it to look up geocoding results in your map or dictionary without relying on array index order. Any long enough, caller-meaningful identifier works (e.g. feed name + row number, database primary key, UUID). Do NOT derive this by hashing the input fields — SearchMode has a server-side default and omitting it from a hash causes silent collisions when the same location appears with different search modes.
	RowKey string `json:"rowKey"`
	// Bias for place search: 'auto' (default) balances area and population. Use 'prefer_larger_area' when the IP range covers an entire state or province. Use 'prefer_larger_population_center' when the IP range is in a metro area and you want the nearest major city.
	SearchMode *string `json:"searchMode,omitempty"`
}

type _InRfc8805RowPlaceSearchParams InRfc8805RowPlaceSearchParams

// NewInRfc8805RowPlaceSearchParams instantiates a new InRfc8805RowPlaceSearchParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInRfc8805RowPlaceSearchParams(countryCode string, rowKey string) *InRfc8805RowPlaceSearchParams {
	this := InRfc8805RowPlaceSearchParams{}
	this.CountryCode = countryCode
	this.RowKey = rowKey
	var searchMode string = "auto"
	this.SearchMode = &searchMode
	return &this
}

// NewInRfc8805RowPlaceSearchParamsWithDefaults instantiates a new InRfc8805RowPlaceSearchParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInRfc8805RowPlaceSearchParamsWithDefaults() *InRfc8805RowPlaceSearchParams {
	this := InRfc8805RowPlaceSearchParams{}
	var searchMode string = "auto"
	this.SearchMode = &searchMode
	return &this
}

// GetCityName returns the CityName field value if set, zero value otherwise.
func (o *InRfc8805RowPlaceSearchParams) GetCityName() string {
	if o == nil || IsNil(o.CityName) {
		var ret string
		return ret
	}
	return *o.CityName
}

// GetCityNameOk returns a tuple with the CityName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchParams) GetCityNameOk() (*string, bool) {
	if o == nil || IsNil(o.CityName) {
		return nil, false
	}
	return o.CityName, true
}

// HasCityName returns a boolean if a field has been set.
func (o *InRfc8805RowPlaceSearchParams) HasCityName() bool {
	if o != nil && !IsNil(o.CityName) {
		return true
	}

	return false
}

// SetCityName gets a reference to the given string and assigns it to the CityName field.
func (o *InRfc8805RowPlaceSearchParams) SetCityName(v string) {
	o.CityName = &v
}

// GetCountryCode returns the CountryCode field value
func (o *InRfc8805RowPlaceSearchParams) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchParams) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *InRfc8805RowPlaceSearchParams) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetRegionCode returns the RegionCode field value if set, zero value otherwise.
func (o *InRfc8805RowPlaceSearchParams) GetRegionCode() string {
	if o == nil || IsNil(o.RegionCode) {
		var ret string
		return ret
	}
	return *o.RegionCode
}

// GetRegionCodeOk returns a tuple with the RegionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchParams) GetRegionCodeOk() (*string, bool) {
	if o == nil || IsNil(o.RegionCode) {
		return nil, false
	}
	return o.RegionCode, true
}

// HasRegionCode returns a boolean if a field has been set.
func (o *InRfc8805RowPlaceSearchParams) HasRegionCode() bool {
	if o != nil && !IsNil(o.RegionCode) {
		return true
	}

	return false
}

// SetRegionCode gets a reference to the given string and assigns it to the RegionCode field.
func (o *InRfc8805RowPlaceSearchParams) SetRegionCode(v string) {
	o.RegionCode = &v
}

// GetRowKey returns the RowKey field value
func (o *InRfc8805RowPlaceSearchParams) GetRowKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RowKey
}

// GetRowKeyOk returns a tuple with the RowKey field value
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchParams) GetRowKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowKey, true
}

// SetRowKey sets field value
func (o *InRfc8805RowPlaceSearchParams) SetRowKey(v string) {
	o.RowKey = v
}

// GetSearchMode returns the SearchMode field value if set, zero value otherwise.
func (o *InRfc8805RowPlaceSearchParams) GetSearchMode() string {
	if o == nil || IsNil(o.SearchMode) {
		var ret string
		return ret
	}
	return *o.SearchMode
}

// GetSearchModeOk returns a tuple with the SearchMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchParams) GetSearchModeOk() (*string, bool) {
	if o == nil || IsNil(o.SearchMode) {
		return nil, false
	}
	return o.SearchMode, true
}

// HasSearchMode returns a boolean if a field has been set.
func (o *InRfc8805RowPlaceSearchParams) HasSearchMode() bool {
	if o != nil && !IsNil(o.SearchMode) {
		return true
	}

	return false
}

// SetSearchMode gets a reference to the given string and assigns it to the SearchMode field.
func (o *InRfc8805RowPlaceSearchParams) SetSearchMode(v string) {
	o.SearchMode = &v
}

func (o InRfc8805RowPlaceSearchParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InRfc8805RowPlaceSearchParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CityName) {
		toSerialize["cityName"] = o.CityName
	}
	toSerialize["countryCode"] = o.CountryCode
	if !IsNil(o.RegionCode) {
		toSerialize["regionCode"] = o.RegionCode
	}
	toSerialize["rowKey"] = o.RowKey
	if !IsNil(o.SearchMode) {
		toSerialize["searchMode"] = o.SearchMode
	}
	return toSerialize, nil
}

func (o *InRfc8805RowPlaceSearchParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"countryCode",
		"rowKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInRfc8805RowPlaceSearchParams := _InRfc8805RowPlaceSearchParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInRfc8805RowPlaceSearchParams)

	if err != nil {
		return err
	}

	*o = InRfc8805RowPlaceSearchParams(varInRfc8805RowPlaceSearchParams)

	return err
}

type NullableInRfc8805RowPlaceSearchParams struct {
	value *InRfc8805RowPlaceSearchParams
	isSet bool
}

func (v NullableInRfc8805RowPlaceSearchParams) Get() *InRfc8805RowPlaceSearchParams {
	return v.value
}

func (v *NullableInRfc8805RowPlaceSearchParams) Set(val *InRfc8805RowPlaceSearchParams) {
	v.value = val
	v.isSet = true
}

func (v NullableInRfc8805RowPlaceSearchParams) IsSet() bool {
	return v.isSet
}

func (v *NullableInRfc8805RowPlaceSearchParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInRfc8805RowPlaceSearchParams(val *InRfc8805RowPlaceSearchParams) *NullableInRfc8805RowPlaceSearchParams {
	return &NullableInRfc8805RowPlaceSearchParams{value: val, isSet: true}
}

func (v NullableInRfc8805RowPlaceSearchParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInRfc8805RowPlaceSearchParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


