/*
Fastah REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geofeed_structs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Location type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Location{}

// Location struct for Location
type Location struct {
	// Confidence radius in kilometers around the center point geo-coordinates in longLat
	AccuracyRadiusKm int64 `json:"accuracyRadiusKm"`
	// The rectangular bounding box of the matched place as [minLong, minLat, maxLong, maxLat], providing the geographic extent of the resolved location.
	BoundingBox []float64 `json:"boundingBox"`
	// 2-letter continent code
	ContinentCode string `json:"continentCode"`
	// ISO 3166-1 alpha-2 country code
	CountryCode string `json:"countryCode"`
	// Country name as a display string
	CountryName string `json:"countryName"`
	// The flag emoji corresponding to the country code (e.g. 🇺🇸 for US, 🇮🇳 for IN)
	FlagEmoji string `json:"flagEmoji"`
	// Array of Uber H3 hexagonal cell indices that cover the geographic extent of this matched place, enabling efficient spatial indexing and hierarchical geofencing.
	H3Cells []string `json:"h3Cells"`
	// Longitude, Latitude representing the approximate geographical center, to be interpreted together with accuracyRadius - the radius in kilometers around this point as a confidence region.
	LongLat []float64 `json:"longLat"`
	// A stable place ID - in this case within the Geonames.org place names database
	PlaceIdGeonames int64 `json:"placeIdGeonames"`
	// Name of the resolved location, which may be a city, region, or country depending on placeType
	PlaceName string `json:"placeName"`
	// The geographic granularity of this location result. A 'city' is the most precise, 'region' indicates a state or province, and 'country' means a country or territory.
	PlaceType string `json:"placeType"`
	// Relative population score (0.0-100.0) indicating the place's population size compared to other places in the dataset
	PopulationWeight float32 `json:"populationWeight"`
	// ISO 3166-1 alpha-2 code of the sovereign country. Equals countryCode for independent nations. Differs for dependent territories, e.g. 'US' when countryCode is 'UM' (US Minor Outlying Islands), or 'GB' when countryCode is 'IO' (British Indian Ocean Territory).
	SovereignCountryCode string `json:"sovereignCountryCode"`
	// ISO 3166-2 code, if available, of the state, province, or top-level administrative subdivision. May be empty for countries without a commonly-used subdivision code.
	StateCode string `json:"stateCode"`
	// Name of the state, province, or top-level administrative subdivision of a country. May be empty for smaller countries without a commonly-used subdivision, or when placeType is 'country'.
	StateName string `json:"stateName"`
	// IANA time zone identifier for this location. May be empty for large-area regions or countries that span multiple time zones.
	Tz string `json:"tz"`
}

type _Location Location

// NewLocation instantiates a new Location object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocation(accuracyRadiusKm int64, boundingBox []float64, continentCode string, countryCode string, countryName string, flagEmoji string, h3Cells []string, longLat []float64, placeIdGeonames int64, placeName string, placeType string, populationWeight float32, sovereignCountryCode string, stateCode string, stateName string, tz string) *Location {
	this := Location{}
	this.AccuracyRadiusKm = accuracyRadiusKm
	this.BoundingBox = boundingBox
	this.ContinentCode = continentCode
	this.CountryCode = countryCode
	this.CountryName = countryName
	this.FlagEmoji = flagEmoji
	this.H3Cells = h3Cells
	this.LongLat = longLat
	this.PlaceIdGeonames = placeIdGeonames
	this.PlaceName = placeName
	this.PlaceType = placeType
	this.PopulationWeight = populationWeight
	this.SovereignCountryCode = sovereignCountryCode
	this.StateCode = stateCode
	this.StateName = stateName
	this.Tz = tz
	return &this
}

// NewLocationWithDefaults instantiates a new Location object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationWithDefaults() *Location {
	this := Location{}
	var placeIdGeonames int64 = 0
	this.PlaceIdGeonames = placeIdGeonames
	return &this
}

// GetAccuracyRadiusKm returns the AccuracyRadiusKm field value
func (o *Location) GetAccuracyRadiusKm() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccuracyRadiusKm
}

// GetAccuracyRadiusKmOk returns a tuple with the AccuracyRadiusKm field value
// and a boolean to check if the value has been set.
func (o *Location) GetAccuracyRadiusKmOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccuracyRadiusKm, true
}

// SetAccuracyRadiusKm sets field value
func (o *Location) SetAccuracyRadiusKm(v int64) {
	o.AccuracyRadiusKm = v
}

// GetBoundingBox returns the BoundingBox field value
func (o *Location) GetBoundingBox() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.BoundingBox
}

// GetBoundingBoxOk returns a tuple with the BoundingBox field value
// and a boolean to check if the value has been set.
func (o *Location) GetBoundingBoxOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoundingBox, true
}

// SetBoundingBox sets field value
func (o *Location) SetBoundingBox(v []float64) {
	o.BoundingBox = v
}

// GetContinentCode returns the ContinentCode field value
func (o *Location) GetContinentCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContinentCode
}

// GetContinentCodeOk returns a tuple with the ContinentCode field value
// and a boolean to check if the value has been set.
func (o *Location) GetContinentCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContinentCode, true
}

// SetContinentCode sets field value
func (o *Location) SetContinentCode(v string) {
	o.ContinentCode = v
}

// GetCountryCode returns the CountryCode field value
func (o *Location) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *Location) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *Location) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetCountryName returns the CountryName field value
func (o *Location) GetCountryName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value
// and a boolean to check if the value has been set.
func (o *Location) GetCountryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryName, true
}

// SetCountryName sets field value
func (o *Location) SetCountryName(v string) {
	o.CountryName = v
}

// GetFlagEmoji returns the FlagEmoji field value
func (o *Location) GetFlagEmoji() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FlagEmoji
}

// GetFlagEmojiOk returns a tuple with the FlagEmoji field value
// and a boolean to check if the value has been set.
func (o *Location) GetFlagEmojiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlagEmoji, true
}

// SetFlagEmoji sets field value
func (o *Location) SetFlagEmoji(v string) {
	o.FlagEmoji = v
}

// GetH3Cells returns the H3Cells field value
func (o *Location) GetH3Cells() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.H3Cells
}

// GetH3CellsOk returns a tuple with the H3Cells field value
// and a boolean to check if the value has been set.
func (o *Location) GetH3CellsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.H3Cells, true
}

// SetH3Cells sets field value
func (o *Location) SetH3Cells(v []string) {
	o.H3Cells = v
}

// GetLongLat returns the LongLat field value
func (o *Location) GetLongLat() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.LongLat
}

// GetLongLatOk returns a tuple with the LongLat field value
// and a boolean to check if the value has been set.
func (o *Location) GetLongLatOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.LongLat, true
}

// SetLongLat sets field value
func (o *Location) SetLongLat(v []float64) {
	o.LongLat = v
}

// GetPlaceIdGeonames returns the PlaceIdGeonames field value
func (o *Location) GetPlaceIdGeonames() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PlaceIdGeonames
}

// GetPlaceIdGeonamesOk returns a tuple with the PlaceIdGeonames field value
// and a boolean to check if the value has been set.
func (o *Location) GetPlaceIdGeonamesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaceIdGeonames, true
}

// SetPlaceIdGeonames sets field value
func (o *Location) SetPlaceIdGeonames(v int64) {
	o.PlaceIdGeonames = v
}

// GetPlaceName returns the PlaceName field value
func (o *Location) GetPlaceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlaceName
}

// GetPlaceNameOk returns a tuple with the PlaceName field value
// and a boolean to check if the value has been set.
func (o *Location) GetPlaceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaceName, true
}

// SetPlaceName sets field value
func (o *Location) SetPlaceName(v string) {
	o.PlaceName = v
}

// GetPlaceType returns the PlaceType field value
func (o *Location) GetPlaceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlaceType
}

// GetPlaceTypeOk returns a tuple with the PlaceType field value
// and a boolean to check if the value has been set.
func (o *Location) GetPlaceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaceType, true
}

// SetPlaceType sets field value
func (o *Location) SetPlaceType(v string) {
	o.PlaceType = v
}

// GetPopulationWeight returns the PopulationWeight field value
func (o *Location) GetPopulationWeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PopulationWeight
}

// GetPopulationWeightOk returns a tuple with the PopulationWeight field value
// and a boolean to check if the value has been set.
func (o *Location) GetPopulationWeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PopulationWeight, true
}

// SetPopulationWeight sets field value
func (o *Location) SetPopulationWeight(v float32) {
	o.PopulationWeight = v
}

// GetSovereignCountryCode returns the SovereignCountryCode field value
func (o *Location) GetSovereignCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SovereignCountryCode
}

// GetSovereignCountryCodeOk returns a tuple with the SovereignCountryCode field value
// and a boolean to check if the value has been set.
func (o *Location) GetSovereignCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SovereignCountryCode, true
}

// SetSovereignCountryCode sets field value
func (o *Location) SetSovereignCountryCode(v string) {
	o.SovereignCountryCode = v
}

// GetStateCode returns the StateCode field value
func (o *Location) GetStateCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StateCode
}

// GetStateCodeOk returns a tuple with the StateCode field value
// and a boolean to check if the value has been set.
func (o *Location) GetStateCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateCode, true
}

// SetStateCode sets field value
func (o *Location) SetStateCode(v string) {
	o.StateCode = v
}

// GetStateName returns the StateName field value
func (o *Location) GetStateName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StateName
}

// GetStateNameOk returns a tuple with the StateName field value
// and a boolean to check if the value has been set.
func (o *Location) GetStateNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateName, true
}

// SetStateName sets field value
func (o *Location) SetStateName(v string) {
	o.StateName = v
}

// GetTz returns the Tz field value
func (o *Location) GetTz() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tz
}

// GetTzOk returns a tuple with the Tz field value
// and a boolean to check if the value has been set.
func (o *Location) GetTzOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tz, true
}

// SetTz sets field value
func (o *Location) SetTz(v string) {
	o.Tz = v
}

func (o Location) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Location) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accuracyRadiusKm"] = o.AccuracyRadiusKm
	toSerialize["boundingBox"] = o.BoundingBox
	toSerialize["continentCode"] = o.ContinentCode
	toSerialize["countryCode"] = o.CountryCode
	toSerialize["countryName"] = o.CountryName
	toSerialize["flagEmoji"] = o.FlagEmoji
	toSerialize["h3Cells"] = o.H3Cells
	toSerialize["longLat"] = o.LongLat
	toSerialize["placeIdGeonames"] = o.PlaceIdGeonames
	toSerialize["placeName"] = o.PlaceName
	toSerialize["placeType"] = o.PlaceType
	toSerialize["populationWeight"] = o.PopulationWeight
	toSerialize["sovereignCountryCode"] = o.SovereignCountryCode
	toSerialize["stateCode"] = o.StateCode
	toSerialize["stateName"] = o.StateName
	toSerialize["tz"] = o.Tz
	return toSerialize, nil
}

func (o *Location) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accuracyRadiusKm",
		"boundingBox",
		"continentCode",
		"countryCode",
		"countryName",
		"flagEmoji",
		"h3Cells",
		"longLat",
		"placeIdGeonames",
		"placeName",
		"placeType",
		"populationWeight",
		"sovereignCountryCode",
		"stateCode",
		"stateName",
		"tz",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocation := _Location{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocation)

	if err != nil {
		return err
	}

	*o = Location(varLocation)

	return err
}

type NullableLocation struct {
	value *Location
	isSet bool
}

func (v NullableLocation) Get() *Location {
	return v.value
}

func (v *NullableLocation) Set(val *Location) {
	v.value = val
	v.isSet = true
}

func (v NullableLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocation(val *Location) *NullableLocation {
	return &NullableLocation{value: val, isSet: true}
}

func (v NullableLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


