/*
Fastah REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geofeed_structs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InRfc8805RowPlaceSearchBatchParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InRfc8805RowPlaceSearchBatchParams{}

// InRfc8805RowPlaceSearchBatchParams struct for InRfc8805RowPlaceSearchBatchParams
type InRfc8805RowPlaceSearchBatchParams struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Batch-friendly geocoding of RFC 8805 CSV (IP geolocation feed) rows, expressed as an JSON array of objects. Each element (JSON object) specifies a required rowKey, required country code, optional region, optional city, and search options. Example: [{\"rowKey\":\"acme-ipv4-feed01-arin/row/000042\",\"countryCode\":\"CA\",\"regionCode\":\"CA-ON\",\"cityName\":\"Toronto\"},{\"rowKey\":\"acme-ipv4-feed01-arin/row/000043\",\"countryCode\":\"IN\",\"regionCode\":\"IN-KA\",\"cityName\":\"Bangalore\"}]
	Rows []InRfc8805RowPlaceSearchParams `json:"rows"`
}

type _InRfc8805RowPlaceSearchBatchParams InRfc8805RowPlaceSearchBatchParams

// NewInRfc8805RowPlaceSearchBatchParams instantiates a new InRfc8805RowPlaceSearchBatchParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInRfc8805RowPlaceSearchBatchParams(rows []InRfc8805RowPlaceSearchParams) *InRfc8805RowPlaceSearchBatchParams {
	this := InRfc8805RowPlaceSearchBatchParams{}
	this.Rows = rows
	return &this
}

// NewInRfc8805RowPlaceSearchBatchParamsWithDefaults instantiates a new InRfc8805RowPlaceSearchBatchParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInRfc8805RowPlaceSearchBatchParamsWithDefaults() *InRfc8805RowPlaceSearchBatchParams {
	this := InRfc8805RowPlaceSearchBatchParams{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *InRfc8805RowPlaceSearchBatchParams) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchBatchParams) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *InRfc8805RowPlaceSearchBatchParams) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *InRfc8805RowPlaceSearchBatchParams) SetSchema(v string) {
	o.Schema = &v
}

// GetRows returns the Rows field value
func (o *InRfc8805RowPlaceSearchBatchParams) GetRows() []InRfc8805RowPlaceSearchParams {
	if o == nil {
		var ret []InRfc8805RowPlaceSearchParams
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *InRfc8805RowPlaceSearchBatchParams) GetRowsOk() ([]InRfc8805RowPlaceSearchParams, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rows, true
}

// SetRows sets field value
func (o *InRfc8805RowPlaceSearchBatchParams) SetRows(v []InRfc8805RowPlaceSearchParams) {
	o.Rows = v
}

func (o InRfc8805RowPlaceSearchBatchParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InRfc8805RowPlaceSearchBatchParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["rows"] = o.Rows
	return toSerialize, nil
}

func (o *InRfc8805RowPlaceSearchBatchParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rows",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInRfc8805RowPlaceSearchBatchParams := _InRfc8805RowPlaceSearchBatchParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInRfc8805RowPlaceSearchBatchParams)

	if err != nil {
		return err
	}

	*o = InRfc8805RowPlaceSearchBatchParams(varInRfc8805RowPlaceSearchBatchParams)

	return err
}

type NullableInRfc8805RowPlaceSearchBatchParams struct {
	value *InRfc8805RowPlaceSearchBatchParams
	isSet bool
}

func (v NullableInRfc8805RowPlaceSearchBatchParams) Get() *InRfc8805RowPlaceSearchBatchParams {
	return v.value
}

func (v *NullableInRfc8805RowPlaceSearchBatchParams) Set(val *InRfc8805RowPlaceSearchBatchParams) {
	v.value = val
	v.isSet = true
}

func (v NullableInRfc8805RowPlaceSearchBatchParams) IsSet() bool {
	return v.isSet
}

func (v *NullableInRfc8805RowPlaceSearchBatchParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInRfc8805RowPlaceSearchBatchParams(val *InRfc8805RowPlaceSearchBatchParams) *NullableInRfc8805RowPlaceSearchBatchParams {
	return &NullableInRfc8805RowPlaceSearchBatchParams{value: val, isSet: true}
}

func (v NullableInRfc8805RowPlaceSearchBatchParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInRfc8805RowPlaceSearchBatchParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


